services:

    #koalityio_server_check_space_used:
    #    class: Leankoala\HealthFoundation\Check\Device\SpaceUsedCheck
    #    calls:
    #        -   method: init
    #            arguments:
    #                - 90

    #koalityio_healthfoundation:
    #    class: Leankoala\HealthFoundation\HealthFoundation
    #    calls:
    #        -   method: registerCheck
    #            arguments:
    #                - '@koalityio_server_check_space_used'
